controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: evgeny
 * Date: 20.06.18
 * Time: 1:22
 */

namespace app\controllers;


use app\models\product\Product;
use app\models\product\ProductCategory;
use app\models\product\ProductImage;
use app\models\product\ProductSubCategory;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\Cookie;

class ProductController extends Controller
{
    public $layout = 'product-layout';
    public function actionIndex($id){

        $product_sub_category = ProductSubCategory::findAll(['product_category_id' => $id]);
        $products = Product::find()->where(['product_category_id' => $id])
        ->andWhere(['product_sub_category' => $product_sub_category[0]['id']])
            ->limit(8)->all();
//        $pages_products = new Pagination(['totalCount' => $query_products->count(), 'pageSize' => 16, 'forcePageParam' => false, 'pageSizeParam' => false]);
//        $products = $query_products->offset($pages_products->offset)->limit($pages_products->limit)->all();
        $category = ProductCategory::findOne($id);
        $this->view->title = $category->name . ' | LEVINTAS JEWERLY';
        $this->view->params['category_image'] = $category->image_category ?? $category->image;
        $this->view->params['category'] = $category->name;
        $this->view->params['description'] = $category->description_category;
        $count_product_category = count($products);
        $declension_view =  $this->declension_word($count_product_category);
        return $this->render('index', [
            'products' => $products,
            'count_product_category' => $count_product_category,
            'product_sub_category' => $product_sub_category,
            'declension_view' => $declension_view,
            'category' => $category
        ]);
    }

    public function actionLoadProduct(){
        if(Yii::$app->request->get()){
            $product_cat_id = Yii::$app->request->get('category_id');
            $product_sub_cat_id = Yii::$app->request->get('sub_category_id');
            $num = Yii::$app->request->get('num');
            $products = Product::find()->where(['product_category_id' => $product_cat_id])
                ->andWhere(['product_sub_category' => $product_sub_cat_id])
                ->offset($num)
                ->limit($num)->all();
            return $this->renderPartial('load-product', [
                'products' => $products
            ]);
        }
    }

    public function actionProduct($id){
        $product = Product::findOne($id);
        $this->view->title = $product->name . ' | LEVINTAS JEWERLY';
        $this->view->params['product_id'] = $product->id;
        $this->view->params['product_image'] = $product->image;
        $this->view->params['product_image_fon'] = $product->productCategory->image;
        $this->view->params['product_name'] = $product->name;
        $this->view->params['product_images'] = ProductImage::findAll(['product_id' => $id]);
        $this->view->params['product_price'] = $product->price;
        $this->view->params['product_weight'] = $product->product_weight;
        $this->view->params['number_of_stones'] = $product->number_of_stones;
        $this->view->params['weight_of_stones'] = $product->weight_of_stones;
        $this->view->params['preparation_time'] = $product->preparation_time;
        $this->view->params['gold_content'] = $product->gold_content;
        $this->view->params['vendor_code'] = $product->vendor_code;
        if(!is_null($product->sale) && !is_null($product->new_price)){
            $this->view->params['product_sale'] = $product->sale;
            $this->view->params['product_new_price'] = $product->new_price;
        }

        return $this->render('product', [
            'product' => $product
        ]);
    }

    public function actionLoadSubcategory(){
        if(Yii::$app->request->post()){
//            if(Yii::$app->request->post('id') != 0){
//                $query_products = Product::find()->where(['product_sub_category' => Yii::$app->request->post('id'),
//                    'product_category_id' => Yii::$app->request->post('cat_id')]);
//                $pages_products = new Pagination(['route' => '/product/index?id='.Yii::$app->request->post('cat_id'), 'totalCount' => $query_products->count(), 'pageSize' => 16, 'forcePageParam' => false, 'pageSizeParam' => false]);
//                $products = $query_products->offset($pages_products->offset)->limit($pages_products->limit)->all();
//
//            }
//            else{
//                $query_products = Product::find()->where(['product_category_id' => Yii::$app->request->post('cat_id')]);
//                $pages_products = new Pagination(['route' => '/product/index?id='.Yii::$app->request->post('cat_id'), 'totalCount' => $query_products->count(), 'pageSize' => 16, 'forcePageParam' => false, 'pageSizeParam' => false]);
//                $products = $query_products->offset($pages_products->offset)->limit($pages_products->limit)->all();
//
//            }

            $products = Product::find()->where(['product_category_id' => Yii::$app->request->post('cat_id')])
                ->andWhere(['product_sub_category' => Yii::$app->request->post('id')])
                ->limit(8)->all();

            return $this->renderPartial('load-subcategory', [
                'products' => $products,
                'sub_category_id' => Yii::$app->request->post('id'),
                'category_id' => Yii::$app->request->post('cat_id')
            ]);
        }
        return false;
    }

    public function actionLoadPrice(){
        if(Yii::$app->request->post()){
            if(Yii::$app->request->post('sub_cat_id') != 0){
                $query_products_not_sale = Product::find()
                    ->where(['product_category_id' => Yii::$app->request->post('cat_id')])
                    ->andWhere(['sale' => null])
                    ->andWhere(['>=', 'price', Yii::$app->request->post('start')])
                    ->andWhere(['<=', 'price', Yii::$app->request->post('end')])
                    ->andWhere(['product_sub_category' => Yii::$app->request->post('sub_cat_id')]);
                $query_products = Product::find()
                    ->where(['product_category_id' => Yii::$app->request->post('cat_id')])
                    ->andWhere(['not', ['sale' => null]])
                    ->andWhere(['>=', 'new_price', Yii::$app->request->post('start')])
                    ->andWhere(['<=', 'new_price', Yii::$app->request->post('end')])
                    ->andWhere(['product_sub_category' => Yii::$app->request->post('sub_cat_id')])
                    ->union($query_products_not_sale);
            }
            else{
                $query_products_not_sale = Product::find()
                    ->where(['product_category_id' => Yii::$app->request->post('cat_id')])
                    ->andWhere(['sale' => null])
                    ->andWhere(['>=', 'price', Yii::$app->request->post('start')])
                    ->andWhere(['<=', 'price', Yii::$app->request->post('end')]);
                $query_products = Product::find()
                    ->where(['product_category_id' => Yii::$app->request->post('cat_id')])
                    ->andWhere(['not', ['sale' => null]])
                    ->andWhere(['>=', 'new_price', Yii::$app->request->post('start')])
                    ->andWhere(['<=', 'new_price', Yii::$app->request->post('end')])
                    ->union($query_products_not_sale);
            }

            $pages_products = new Pagination(['totalCount' => $query_products->count(), 'pageSize' => 4, 'forcePageParam' => false, 'pageSizeParam' => false]);
            $products = $query_products->offset($pages_products->offset)->limit($pages_products->limit)->all();

            return $this->renderPartial('load-price', [
                'products' => $products,
                'pages_products' => $pages_products
            ]);
        }
        return false;
    }

    public function actionAddBasket(){
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id_product');
            $array_count = Yii::$app->request->cookies->getValue('basket');//сooc->get('basket');
            if(empty($array_count)){
                Yii::$app->response->cookies->add(new Cookie([
                    'name' => 'basket',
                    'value' => array((int)$id),
                ]));
                return true;
            }
            else{
                if(!in_array($id,$array_count)){
                    $array_merge =  array_merge($array_count, array((int)$id));
                    Yii::$app->response->cookies->remove('basket');
                    Yii::$app->response->cookies->add(new Cookie([
                        'name' => 'basket',
                        'value' => $array_merge,
                    ]));
                    return true;
                }
            }
        }

        return false;
    }

    public function actionDeleteBasket(){
        if(Yii::$app->request->post()){
            $id = Yii::$app->request->post('id_product');
            $array_count = Yii::$app->request->cookies->getValue('basket');
            if(empty($array_count)){
                return false;
            }
            else{
                if(in_array($id, $array_count)){
                    $key = array_search($id, Yii::$app->request->cookies->getValue('basket'));
                    unset($array_count[$key]);
                    Yii::$app->response->cookies->remove('basket');
                    Yii::$app->response->cookies->add(new Cookie([
                        'name' => 'basket',
                        'value' => $array_count,
                    ]));
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Function declension word
     *
     * @param $number
     * @param array $word
     * @return mixed
     */

views/product/index.php
<?php

use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="<?= Url::home() ?>">Главная</a> /
            <span><?= $category->name ?></span>
        </div>
    </div>

    <div class="main__catalog catalog-page page-content">
        <div class="container">
            <div class="catalog-page__quantity">
                <span><?= $count_product_category ?> <?= $declension_view ?></span>
            </div>

            <form action="" class="catalog-page__filter filter">
                <div class="filter__category">
                    <?php foreach ($product_sub_category as $key => $value): ?>
                        <label>
                            <input value="<?= $value->id ?>" data-id="<?= $category->id ?>" type="radio"
                                   name="category" <?= $key == 0 ? 'checked' : '' ?> >
                            <div class="filter__radio" style="background-image: url(<?= $value->image ?>)">
                                <div class="filter__border"></div>
                                <span><?= $value->name ?></span>
                            </div>
                        </label>
                    <?php endforeach; ?>

                </div>

            </form>

            <div class="result-upload-product"></div>

            <div class="catalog-page__content">
                <div class="grid grid_4">
                    <div class="upload_loader" style="text-align: center; display:none ">
                        <img class="" src="/img/loader.gif" alt="Loading...">
                    </div>
                    <?php foreach ($products as $product): ?>
                        <div class="grid__item">
                            <a class="product <?= !is_null($product['sale']) ? 'sale' : '' ?>"
                               href="<?= Url::to(['/product/product', 'id' => $product->id]) ?>">
                                <?= !is_null($product['sale']) ? '<div class="product__sale">' . $product['sale'] . '</div>' : '' ?>
                                <div class="product__img">
                                    <img src="<?= $product->image ?>" alt="<?= $product->name ?>">
                                </div>

<!--                                <div class="product__title">-->
<!--                                    <h3>--><?//= $product->name ?><!--</h3>-->
<!--                                </div>-->
                                <div class="product__price">
                                    <span><?= $product->price ?></span>
                                    <?= !is_null($product['sale']) ? '<span>'. $product['new_price'] .'</span>' : '' ?>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>
                    <div class="result-upload-product_load"></div>
                    <div class="catalog-page__load_button" style=" text-align: center;
                        font-size: 24px;
                        background-color: #232326;
                        color: white;
                            margin-top: 21px;
                        border-radius: 6px; display: <?= count($products) != 8 ? 'none' : '' ?>">
                        <button data-id="<?= $product_sub_category[0]['id'] ?>"
                                data-num="8"
                                data-cat="<?= $category->id ?>"
                                class="load_product"
                                type="button">Показать еще</button>
                    </div>
                    <div class="catalog-page__empty" style="display: none">
                        <p>По вашим критериям ничего не найдено</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

views/product/load-price.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
    <div class="catalog-page__content">
        <div class="grid grid_4">
            <div class="upload_loader" style="text-align: center; display:none ">
                <img class="" src="/img/loader.gif" alt="Loading...">
            </div>
            <?php foreach ($products as $product):?>
                <div class="grid__item">
                    <a class="product <?= !is_null($product['sale']) ? 'sale' : '' ?>" href="<?= Url::to(['/product/product', 'id' => $product->id]) ?>">
                        <?= !is_null($product['sale']) ? '<div class="product__sale">'. $product['sale'] .'</div>' : '' ?>
                        <div class="product__img">
                            <img src="<?= $product->image ?>" alt="<?= $product->name ?>">
                        </div>

                        <div class="product__title">
                            <h3><?= $product->name ?></h3>
                        </div>

                        <div class="product__price">
                            <span><?= $product->price ?></span>
                            <?= !is_null($product['sale']) ? '<span>'. $product['new_price'] .'</span>' : '' ?>

                        </div>
                    </a>
                </div>
            <?php endforeach;?>
            <div class="catalog-page__empty" style="display: none">
                <p>По вашим критериям ничего не найдено</p>
            </div>
        </div>
    </div>
<?= '<div class="catalog-page__pagination pagination">' . LinkPager::widget([
    'pagination' => $pages_products,
    'prevPageCssClass' => 'prev',
    'nextPageCssClass' => 'next',
]) . '</div>'; ?>

views/product/load-product.php
<?php
use yii\helpers\Url;
?>
<?php foreach ($products as $product):?>
    <div class="grid__item">
        <a class="product <?= !is_null($product['sale']) ? 'sale' : '' ?>" href="<?= Url::to(['/product/product', 'id' => $product->id]) ?>">
            <?= !is_null($product['sale']) ? '<div class="product__sale">'. $product['sale'] .'</div>' : '' ?>
            <div class="product__img">
                <img src="<?= $product->image ?>" alt="<?= $product->name ?>">
            </div>

<!--            <div class="product__title">-->
<!--                <h3>--><?//= $product->name ?><!--</h3>-->
<!--            </div>-->
            <div class="product__price">
                <span><?= $product->price ?></span>
                <?= !is_null($product['sale']) ? '<span>'. $product['new_price'] .'</span>' : '' ?>
            </div>
        </a>
    </div>
<?php endforeach;?>

views/product/load-subcategory.php
<?php

use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
<div class="catalog-page__content">
    <div class="grid grid_4">
        <div class="upload_loader" style="text-align: center; display:none ">
            <img class="" src="/img/loader.gif" alt="Loading...">
        </div>
        <?php foreach ($products as $product): ?>
            <div class="grid__item">
                <a class="product <?= !is_null($product['sale']) ? 'sale' : '' ?>"
                   href="<?= Url::to(['/product/product', 'id' => $product->id]) ?>">
                    <?= !is_null($product['sale']) ? '<div class="product__sale">' . $product['sale'] . '</div>' : '' ?>
                    <div class="product__img">
                        <img src="<?= $product->image ?>" alt="<?= $product->name ?>">
                    </div>

<!--                    <div class="product__title">-->
<!--                        <h3>--><?//= $product->name ?><!--</h3>-->
<!--                    </div>-->
                    <div class="product__price">
                        <span><?= $product->price ?></span>
                        <?= !is_null($product['sale']) ? '<span>'. $product['new_price'] .'</span>' : '' ?>
                    </div>
                </a>
            </div>
        <?php endforeach; ?>
        <div class="result-upload-product_load"></div>
        <div class="catalog-page__load_button" style=" text-align: center;
    font-size: 24px;
    background-color: #232326;
        margin-top: 21px;
    color: white;
    border-radius: 6px; display: <?= count($products) != 8 ? 'none' : '' ?>">
        <button data-id="<?= $sub_category_id ?>" data-cat="<?= $category_id ?>" data-num="8" class="load_product"
                type="button">Показать еще
        </button>
    </div>
    <div class="catalog-page__empty" style="display: none">
        <p>По вашим критериям ничего не найдено</p>
    </div>
</div>

views/product/product.php
<?php
use yii\helpers\Url;
?>
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="<?=Url::home()?>">Главная</a> /
            <span><?= $product->productSubCategories->name ?></span>
        </div>
    </div>

    <div class="card-page page-content">
        <div class="container">
            <div class="card-page__title">
                <h2>Описание продукта</h2>
            </div>

            <div class="card-page__columns">
                <p><?= $product->description ?></p>
        </div>
    </div>
</main>