controllers/PageController.php
<?php
/**
 * Created by PhpStorm.
 * User: evgeny
 * Date: 20.06.18
 * Time: 12:10
 */

namespace app\controllers;


use app\models\Application;
use app\models\FormSubmit;
use app\models\Mailer;
use app\models\News;
use app\models\product\Product;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;

class PageController extends Controller
{
    public $layout = 'page-layout';

    public function actionServices(){
        $this->view->title = 'Услуги | LEVINTAS JEWERLY';
        $this->view->params['image_background'] = 'img/services-header-bg.jpg';
        return $this->render('services');
    }

    public function actionAbout(){
        $this->view->title = 'О нас | LEVINTAS JEWERLY';
        $this->view->params['image_background'] = 'img/about-header-bg.jpg';
        return $this->render('about');
    }

    public function actionContacts(){
        $this->view->title = 'Контакты | LEVINTAS JEWERLY';
        $this->view->params['image_background'] = 'img/contacts-header-bg.jpg';
        return $this->render('contacts');
    }

    public function actionNews(){
        $this->layout = 'news-layout';
        $this->view->title = 'Новости | LEVINTAS JEWERLY';
        $this->view->params['image_background'] = 'img/articles-img.jpg';
        $this->view->params['title'] = 'Новости';
        $this->view->params['subtitle'] = 'Кроме продажы готовых изделий наша компания занимается изготовлением уникальных украшений на заказ';
        $query_news = News::find()->where(['is_published' => News::PUBLISH]);
        $pages_news = new Pagination(['totalCount' => $query_news->count(), 'pageSize' => 6, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $news = $query_news->offset($pages_news->offset)->limit($pages_news->limit)->all();
        return $this->render('news', [
            'pages_news' => $pages_news,
            'news' => $news
        ]);
    }

    public function actionSingleNews($id){
        $this->layout = 'news-layout';
        $news = News::findOne($id);
        $this->view->title = $news->name;
        $this->view->params['image_background'] = $news->image;
        $this->view->params['title'] = $news->name;
        return $this->render('single-news', [
            'news' => $news
        ]);
    }

    public function actionBasket(){
        $this->layout = 'basket-layout';
        $this->view->title = 'Корзина | LEVINTAS JEWERLY';
        $model = new Application();
        if($model->load(Yii::$app->request->post())){
            $recaptcha_secret = "6Lev9WAUAAAAAJslvgj0YPRT__wvj4S8leHL_cYu";

            $response = file_get_contents("https://www.google.com/recaptcha/api/siteverify?secret=".$recaptcha_secret."&response=".$_POST['g-recaptcha-response']."&remoteip=".$_SERVER['REMOTE_ADDR']);

            $response = json_decode($response, true);

            if($response["success"] === true) {
                if($model->save()){
                    $name_order = '';
                    foreach (unserialize($model->ids_product) as $value){
                        $order = Product::findOne($value);
                        $name_order .= $order->name . ', ';
                    }

                    $mailer = new Mailer();
                    $mailer->sendApplication('Заявка',
                        $model->name,
                        $model->phone,
                        $name_order);
                    Yii::$app->response->cookies->remove('basket');
                    Yii::$app->session->set('applicationFormSubmitted', 'yes');
                    return $this->redirect('basket');
                }
            }

        }
        return $this->render('basket', [
            'model' => $model
        ]);
    }

}

views/page/about.php
<main class="main">
    <div class="main__team team-page page-content">
        <div class="container">
            <div class="team-page__title">
                <h2>Levintas-jewelry</h2>
            </div>

            <hr>

            <div class="team-page__subtitle">
                <p>Мы созданы чтоб исполнять ваши мечты</p>
            </div>

            <div class="team-page__person">
                <div class="team-page__person-border"></div>
                <div class="team-page__person-img-wrap object-fit-container cover">
                    <!--                        <div class="team__person-img"></div>-->
                    <img src="/img/person-img.jpg" alt="">
                </div>

                <div class="team-page__person-content-wrap">
                    <div class="team-page__person-content">
                        <div class="team-page__person-title">
                            <span>Igor levintas</span>
                        </div>

                        <div class="team-page__person-post">
                            <span>«Ювелирное украшение имеет душу, она зарождается в руках мастера»</span>
                        </div>

                        <div class="team-page__person-text">
                            <p>Игорь Левинтас - мастер ювелир со стажем работы более 20 лет , учился ювелирному мастерству в школе ювелирного мастерства в Израиле, и работал в одних из самых крупных ювелирных компаний Израиля и России. Последнии 10 лет работает в авторской ювелирной студии Levintas-Jewelery.</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="team-page__title2">
                <h2>О нас</h2>
            </div>

            <hr>

            <div class="team-page__columns">
                <p>Добро пожаловать в ювелирную студию Игоря Левинтаса.</p>
                <p>Студия Levintas-jewelry производит эксклюзивные ювелирные украшения на заказ, у нас полный спектр производства по изготовлению украшений. Индивидуальный подход к каждому клиенту учитывая его пожелания, стоимость украшения, дизайн, цвет золота, использование драгоценных и полудрагоценных камней. Все украшения изготовляются в единичном экземпляре и только для Вас. Ювелирные украшения на заказ как правило это экономия вашего бюджета от 40-50% от стоимости украшения в магазине.</p>
                <p>С нами работает команда профессиональных художников-модельеров которые с лёгкостью
                    подготовят модель украшения учитывая ваши пожелания, так же есть возможность изготовления
                    украшений по вашей картинке или фотографии. Мы превратим любой эскиз в реальное
                    произведение искусства.</p>
                <p>Затем украшения попадают в руки мастера и выполняются в ручную, с душой и любовью создаются ослепительной красоты украшения, которые будут радовать вас долгие долгие годы.</p>
            </div>
        </div>
    </div>
</main>

views/page/basket.php
<?php
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

?>
<?php if (Yii::$app->session->has('applicationFormSubmitted')) { ?>

    <?php
    $text_app =  'Ваш заказ оставлен';
    $this->registerJs(
        "alert('$text_app');",
        yii\web\View::POS_READY
    );
    ?>
    <?php Yii::$app->session->remove('applicationFormSubmitted') ?>
<?php } ?>
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="<?= Url::home()?>">Главная</a> /
            <span>Корзина</span>
        </div>
    </div>

    <div class="card-page page-content">
        <div class="container">
            <div class="card-page__title">
                <h3>Оформить заявку</h3>
            </div>

            <?php $form = ActiveForm::begin([
                'id' =>'form_application',
                'options' => [
                    'class' => 'contacts-page__form form'
                ],
                'validateOnBlur' => false
            ]);?>
            <?= $form->field($model, 'ids_product')
                ->hiddenInput(['value' => !empty(Yii::$app->request->cookies->getValue('basket')) ?  serialize(Yii::$app->request->cookies->getValue('basket')) : '']) ?>

            <div class="contacts-page__form-left">
                <?= $form->field($model, 'text')->textarea(['placeholder' => 'Введите текст']) ?>
            </div>
            <div class="contacts-page__form-right">
                <?= $form->field($model, 'name')->textInput(['placeholder' => 'Введите имя']) ?>
                <?= $form->field($model, 'phone')->widget(MaskedInput::className(), [
                    'mask' => '+7 (999) 999-9999',
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => ('Введите номер телефона')
                    ],
                    'clientOptions' => [
                        'clearIncomplete' => true
                    ]

                ])?>
                <?= $form->field($model, 'is_confirm', ['options' => ['class' => 'form__check']])
                    ->checkbox(['label' => '<span>Я соглашаюсь на обработку персональных данных</span>']); ?>

                <!--    <input type="text">-->
                <!--    <input type="email">-->
                <!--    <label class="form__check">-->
                <!--        <input type="checkbox" name="agree">-->
                <!--        <span>Согласие на обработку персональных данных</span>-->
                <!--    </label>-->
                <input class="g-recaptcha"
                       data-sitekey="6Lev9WAUAAAAAPqfp7Pdc8R54DN8V9Uj8jC49X36"
                       data-callback="onSubmitApplication" type="submit" value="Отправить">
            </div>
            <?php ActiveForm::end();?>
        </div>
    </div>
</main>

views/page/news.php
<?php
use yii\helpers\Url;
use yii\widgets\LinkPager;

?>
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="#">Главная</a> /
            <span>Новости</span>
        </div>
    </div>

    <div class="articles-page page-content">
        <div class="container">
            <div class="articles-page__content">
                <div class="grid grid_3">
                    <?php foreach ($news as $item):?>
                        <div class="grid__item">
                            <a class="article" href="<?= Url::to(['page/single-news', 'id' => $item->id, 'slug' => $item->slug]) ?>">
                                <div class="article__img object-fit-container cover">
                                    <img src="<?= $item->image ?>" alt="<?= $item->name ?>">
                                </div>
    
                                <div class="article__content">
                                    <div class="article__date">
                                        <span><?= Yii::$app->formatter->asDate($item->created_at)?></span>
                                    </div>

                                    <div class="article__title">
                                        <h2><?= $item->name ?></h2>
                                    </div>

                                    <div class="article__text">
                                        <p><?= $item->short_description ?></p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>

            <?= '<div class="catalog-page__pagination pagination">' . LinkPager::widget([
                'pagination' => $pages_news,
                'prevPageCssClass' => 'prev',
                'nextPageCssClass' => 'next',
            ]) . '</div>'; ?>
        </div>
    </div>
</main>

views/page/services.php
<?php
use yii\helpers\Url;
?>
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="#">Главная</a> /
            <span>Услуги</span>
        </div>
    </div>

    <div class="main__services services-page page-content">
        <div class="container">
            <div class="services-page__item">
                <div class="services-page__title">
                    <h2>Изготовление на заказ</h2>
                </div>

                <div class="services-page__content">
                    <div class="services-page__img">
                        <div class="services-page__border"></div>
                        <img src="/img/services-page-img1.jpg" alt="">
                    </div>

                    <p>Изготовление на заказ колец, серёжек, кулонов, подвесок, браслетов, цепей, запонок, зажимов для галстуков, фигурок и других изделий из платины, золота и серебра. Создание 3D модели украшения для дальнейшего согласования заказа. Гарантия качества ювелирных украшений это прохождение и наличие клейма Государственной Инспекции Пробирного Надзора. Также наша студия предлагает широкий спектр услуг ремонтных и реставрационных работ кроме этого выполняем такие работы, как:</p>

                    <ul>
                        <li>лазерная пайка;</li>
                        <li>гравировка;</li>
                        <li>нанесение эмали;</li>
                        <li>родирование и золочение;</li>
                        <li>нанесение эмали любого цвета (как горячей, так и холодной);</li>
                        <li>родирование;</li>
                        <li>увеличение/уменьшение размера кольца;</li>
                        <li>пайка цепочек.</li>
                    </ul>

                    <a class="services-page__link" href="<?= Url::home() ?>#collections">Перейти в каталог</a>
                </div>
            </div>

            <div class="services-page__item">
                <div class="services-page__title">
                    <h2>Мастерская по ремонту</h2>
                </div>

                <div class="services-page__content">
                    <div class="services-page__img">
                        <div class="services-page__border"></div>
                        <img src="/img/services-page-img1.jpg" alt="">
                    </div>

                    <p>Мастерская выполняет как отмеченные услуги в прейскуранте, так и другие, например:</p>

                    <ul>
                        <li>правка замка серьги (английского замка);</li>
                        <li>укорачивание и удлинение цепочки или браслета;</li>
                        <li>пайка треснутых (отломанных частей) колец, сережек и кулонов;</li>
                        <li>шлифовка изделий (устранение мелких и глубоких царапин);</li>
                        <li>закрепка жемчуга на кольца, серьги и подвески;</li>
                        <li>восстановление перетертых ушек на крестике;</li>
                        <li>восстановление перетертых колечек на серьгах, цепях и браслетах;</li>
                        <li>изготовление утерянных частей сережек (элемент замка серьги – «палочка» или «крючок»).</li>
                    </ul>

                    <p>Если представленные в нашем каталоге модели Вам не подошли, присылайте фото и описания украшения на почту.</p>

                    <p>Внимание! Перед приездом к нам в офис, просим Вас заранее сообщать (звонить) о Вашем визите.</p>

                    <h3>Цена</h3>

                    <h4>Ремонт изделий из золота 585, 750 пробы:</h4>

                    <ul>
                        <li>Пайка одного места:
                            <ul>
                                <li>Цепи и браслеты - от 500 руб.</li>
                                <li>Кольца и серьги - от 700 руб.</li>
                            </ul>
                        </li>

                        <li>Уменьшение и увеличение колец на 1 размер:
                            <ul>
                                <li>Обручальное кольцо - от 500 руб.</li>
                                <li>Обручальное кольцо с камнями - от 700 руб.</li>
                                <li>Кольца с полудрагоценными камнями - от 700 руб.</li>
                                <li>Кольца с драгоценными камнями (от 0,01 до 0,10 карат) - от 1000 руб.</li>
                            </ul>
                        </li>

                        <li>Ремонт замков на цепях и браслетах:
                            <ul>
                                <li>Замок карабин:
                                    <ul>
                                        <li>Маленький карабин - от 1000 руб.</li>
                                        <li>Средний карабин - от 1200 руб.</li>
                                        <li>Большой карабин - от 1500 руб.</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li>Закрепка (раскрепка) камней:
                            <ul>
                                <li>Полудрагоценных камней:
                                    <ul>
                                        <li>(от 0,01 до 0,10 карат) - от 200 руб.</li>
                                        <li>(от 0,10 до 0,30 карат) - от 300 руб.</li>
                                    </ul>
                                </li>

                                <li>Драгоценных камней:
                                    <ul>
                                        <li>(от 0,01 до ,10 карат) - от 400 руб.</li>
                                        <li>(от 0,10 до 0,30 карат) - от 800 руб.</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>

                        <li>Уход за ювелирными изделиями:
                            <ul>
                                <li>Полировка изделия до 10 гр. - от 500 руб.</li>
                                <li>Очистка ультразвуком - от 200 руб.</li>
                                <li>Определение пробы одного изделия - 100 руб.</li>
                            </ul>
                        </li>
                    </ul>

                    <h4>Ремонт изделий из серебра 925 пробы:</h4>

                    <ul>
                        <li>Пайка одного места:
                            <ul>
                                <li>Цепи и браслеты - от 300 руб.</li>
                                <li>Кольца и серьги без камней - от 500 руб.</li>
                                <li>Кольца и серьги с камнями - от 700 руб.</li>
                            </ul>
                        </li>

                        <li>Покрытие (гальваника) - золочение, родирование, чернение серебра - от 500 руб.</li>

                        <li>Родирование - защитное покрытие платиновой группы для белого золота и серебра - от 800 руб.</li>

                        <li>Эмалирование (холодная эмаль) - от 1500 руб.</li>

                        <li>Наложение горячей эмали одного цвета за один фрагмент - от 2000 руб.</li>

                        <li>Гравировка (алмазная и лазерная):
                            <ul>
                                <li>Алмазная гравировка (гарантия 10 лет!) - 1500 руб.</li>
                                <li>Лазерная гравировка (пожизненная гарантия!) - 2000 руб.</li>
                                <li>Лазерная гравировка, на двух обручальных кольцах (пожизненная гарантия!) - от 2500 руб.</li>
                            </ul>
                        </li>

                        <li>Лазерная пайка (сварка):
                            <ul>
                                <li>Лазерная пайка ювелирных изделий и бижутерии (гарантия 1 год!) - от 700 руб.</li>
                            </ul>
                        </li>
                    </ul>

                    <a class="services-page__link" href="/contacts">Связаться с нами</a>
                </div>
            </div>
        </div>
    </div>
</main>

views/page/single-news.php
<main class="main">
    <div class="main__nav-line">
        <div class="container">
            <a href="#">Главная</a> / <a href="/news">Новости</a> /
            <span><?= $news->name ?></span>
        </div>
    </div>

    <div class="main__article article-page">
        <div class="container">
            <div class="article-page__date">
                <span><?= Yii::$app->formatter->asDate($news->created_at)?></span>
            </div>
            <h1><?= $news->name ?></h1>

            <p><?=  $news->full_description?></p>
        </div>
    </div>
</main>